### ISSUE TITLE
Error al compilar con pandoc

### ISSUE THREAD

**Issue by BlancaCC** [rjraya/Ring-Theory#2]
He intentado compilar con pandoc álgebra1.tex, dejo el código de error que recivo: 
pandoc algebra1.tex -o algebra1.pdf
! LaTeX Error: \ALG @nameundefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.72 \renewcommand{\ALG@name}

pandoc: Error producing PDF

**Comment by rjraya** [comment]
Hola, no sé muy bien como funciona pandoc, pero yo usaba texmaker/texstudio con la configuración PdfLatex + Bib(la)tex + PdfLatex (x2) + Ver Pdf. Espero que te sea de ayuda.

Rodrigo
